# Generated by Django 5.1.5 on 2025-07-29 15:30

import apps.sat.store
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='English_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.CharField(choices=[('module_1', 'Module 1'), ('module_2', 'Module 2')], max_length=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/question_images', verbose_name='Image')),
                ('number', models.IntegerField(null=True, verbose_name='Question Number')),
                ('passage', models.TextField(blank=True, null=True, verbose_name='Passage')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('a', models.TextField(blank=True, null=True, verbose_name='Choice A')),
                ('b', models.TextField(blank=True, null=True, verbose_name='Choice B')),
                ('c', models.TextField(blank=True, null=True, verbose_name='Choice C')),
                ('d', models.TextField(blank=True, null=True, verbose_name='Choice D')),
                ('graph', models.BooleanField(default=False, verbose_name='Is there Graph or Table')),
                ('answer', models.CharField(blank=True, max_length=400, null=True, verbose_name='Answer')),
                ('explained', models.TextField(blank=True, null=True, verbose_name='Explanation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_packages/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Lesson Package',
                'verbose_name_plural': 'Lesson Packages',
            },
        ),
        migrations.CreateModel(
            name='Math_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.CharField(choices=[('module_1', 'Module 1'), ('module_2', 'Module 2')], max_length=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/question_images', verbose_name='Image')),
                ('number', models.IntegerField(null=True, verbose_name='Question Number')),
                ('passage', models.TextField(blank=True, null=True, verbose_name='Passage')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('a', models.TextField(blank=True, null=True, verbose_name='Choice A')),
                ('b', models.TextField(blank=True, null=True, verbose_name='Choice B')),
                ('c', models.TextField(blank=True, null=True, verbose_name='Choice C')),
                ('d', models.TextField(blank=True, null=True, verbose_name='Choice D')),
                ('image_a', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image A')),
                ('image_b', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image B')),
                ('image_c', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image C')),
                ('image_d', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image D')),
                ('graph', models.BooleanField(default=False, verbose_name='Is there Graph or Table')),
                ('choice_graph', models.BooleanField(default=False, verbose_name='Is there Graph or Table in choices')),
                ('written', models.BooleanField(default=False, verbose_name='Is it write type question')),
                ('answer', models.CharField(blank=True, max_length=400, null=True, verbose_name='Answer')),
                ('explained', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('img_explain', models.ImageField(blank=True, null=True, storage=apps.sat.store.PublicStorage(), upload_to='sat/question_images', verbose_name='Image Explanation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_type', models.CharField(choices=[('lesson', 'Lesson Video'), ('test_solved', 'Test Solved Video')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, help_text='Uploaded externally; not via the admin panel.', null=True, storage=apps.sat.store.PrivateStorage(), upload_to='videos/raw/')),
                ('hls_url', models.URLField(blank=True, help_text='URL to the HLS manifest (e.g., output.m3u8) after processing.', null=True)),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('access_token', models.CharField(blank=True, help_text='Token used for generating secure access to the video.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Both', 'Both')], default='Both', max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='sat.lessonpackage')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('videos_watched', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progresses',
            },
        ),
        migrations.CreateModel(
            name='MakeupTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MakeupTestEnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within this makeup test')),
                ('english_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.english_question')),
                ('makeup_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.makeuptest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('makeup_test', 'english_question')},
            },
        ),
        migrations.AddField(
            model_name='makeuptest',
            name='english_questions',
            field=models.ManyToManyField(blank=True, related_name='makeup_tests_english', through='sat.MakeupTestEnglishQuestion', to='sat.english_question'),
        ),
        migrations.CreateModel(
            name='MakeupTestMathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within this makeup test')),
                ('makeup_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.makeuptest')),
                ('math_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.math_question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('makeup_test', 'math_question')},
            },
        ),
        migrations.AddField(
            model_name='makeuptest',
            name='math_questions',
            field=models.ManyToManyField(blank=True, related_name='makeup_tests_math', through='sat.MakeupTestMathQuestion', to='sat.math_question'),
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(null=True, verbose_name='Name of the punishment')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='When happened')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='math_question',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.questiondomain'),
        ),
        migrations.AddField(
            model_name='english_question',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.questiondomain'),
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.questiondomain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='math_question',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.questiontype'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.questiontype'),
        ),
        migrations.AddField(
            model_name='english_question',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.questiontype'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='tests', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecretCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(help_text="6-digit secret code (e.g., '123456')", max_length=6, unique=True)),
                ('group', models.ForeignKey(help_text='Group to add the user to when the code is entered', on_delete=django.db.models.deletion.CASCADE, related_name='secret_codes', to='auth.group')),
                ('makeup_test', models.ForeignKey(blank=True, help_text='Optional: Makeup test to start after entering the code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_codes', to='sat.makeuptest')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_codes', to='sat.test')),
            ],
            options={
                'verbose_name': 'Secret Code',
                'verbose_name_plural': 'Secret Codes',
            },
        ),
        migrations.AddField(
            model_name='math_question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.test'),
        ),
        migrations.AddField(
            model_name='english_question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.test'),
        ),
        migrations.CreateModel(
            name='TestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('score', models.IntegerField(default=400, null=True)),
                ('certificate', models.TextField(blank=True)),
                ('domains', models.BooleanField(default=False)),
                ('test_type', models.CharField(choices=[('regular', 'Regular Test'), ('makeup', 'Makeup Test')], default='regular', max_length=20)),
                ('makeup_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_test_reviews', to='sat.makeuptest')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_reviews', to='sat.test')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasedLessonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='sat.lessonpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'package')},
            },
        ),
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('section', models.CharField(max_length=8)),
                ('module', models.CharField(blank=True, choices=[('m1', 'Module 1'), ('m2', 'Module 2')], max_length=8, null=True)),
                ('answers', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('test_type', models.CharField(choices=[('regular', 'Regular Test'), ('makeup', 'Makeup Test')], default='regular', max_length=20)),
                ('makeup_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_modules', to='sat.makeuptest')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='sat.test')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test', 'makeup_test', 'section', 'module')},
            },
        ),
        migrations.CreateModel(
            name='TestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.IntegerField()),
                ('again', models.BooleanField(default=True)),
                ('retake_count', models.IntegerField(default=0, help_text='Number of retakes used by this user')),
                ('test_type', models.CharField(choices=[('regular', 'Regular Test'), ('makeup', 'Makeup Test')], default='regular', max_length=20)),
                ('makeup_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_test_stages', to='sat.makeuptest')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_stages', to='sat.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
    ]
