# Generated by Django 5.1.5 on 2026-03-24 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0004_classroom_chatmessage_classroomjoincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('first_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('access_code', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('show_score_immediately', models.BooleanField(default=True)),
                ('show_leaderboard', models.BooleanField(default=False)),
                ('allow_resume', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_events', to='sat.test')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEventAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_score', models.IntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('answered_questions', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='sat.globalevent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='sat.guestparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEventAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('english', 'English'), ('math', 'Math')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=10)),
                ('question_id', models.PositiveIntegerField()),
                ('selected_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sat.globaleventattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'section', 'module', 'question_id'), name='unique_global_answer_per_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='globaleventattempt',
            constraint=models.UniqueConstraint(fields=('event', 'guest'), name='unique_guest_attempt_per_event'),
        ),
    ]
