# Generated by Django 5.1.5 on 2026-03-27 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0005_guestparticipant_globalevent_globaleventattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPracticeTestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_test_access', to='sat.classroommembership')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_practice_access', to='sat.test')),
            ],
            options={
                'ordering': ['test__name'],
                'unique_together': {('membership', 'test')},
            },
        ),
    ]
