# Generated by Django 5.1.5 on 2026-03-27 20:24

import apps.sat.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0006_studentpracticetestaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded externally; not via the admin panel.', null=True, storage=apps.sat.storages.PrivateStorage(), upload_to='videos/raw/'),
        ),
        migrations.AlterField(
            model_name='english_question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/question_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='math_question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/question_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='math_question',
            name='image_a',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image A'),
        ),
        migrations.AlterField(
            model_name='math_question',
            name='image_b',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image B'),
        ),
        migrations.AlterField(
            model_name='math_question',
            name='image_c',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image C'),
        ),
        migrations.AlterField(
            model_name='math_question',
            name='image_d',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/choice_images', verbose_name='Image D'),
        ),
        migrations.AlterField(
            model_name='math_question',
            name='img_explain',
            field=models.ImageField(blank=True, null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/question_images', verbose_name='Image Explanation'),
        ),
    ]
