# Generated by Django 5.1.5 on 2026-04-07 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0007_alter_basevideo_video_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodule',
            options={'ordering': ['created']},
        ),
        migrations.AlterUniqueTogether(
            name='testmodule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teststage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testmodule',
            name='attempt_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
