# Generated by Django 5.1.5 on 2026-04-07 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0008_alter_testmodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreview',
            name='attempt_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='teststage',
            name='attempt_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
