# Generated by Django 5.1.5 on 2026-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0009_testreview_attempt_id_teststage_attempt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalevent',
            name='always_live',
            field=models.BooleanField(default=False, help_text='If checked, event is available 24/7 regardless of start/end times'),
        ),
    ]
