# Generated by Django 5.1.5 on 2026-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0010_globalevent_always_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaleventattempt',
            name='current_module_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current module started', null=True),
        ),
        migrations.AlterField(
            model_name='globalevent',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes for each module (total time = duration_minutes × number of modules)'),
        ),
    ]
