# Generated by Django 5.1.5 on 2026-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0011_globaleventattempt_current_module_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalevent',
            name='english_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes for each English module.'),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='math_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes for each Math module.'),
        ),
        migrations.AlterField(
            model_name='globalevent',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Fallback duration in minutes for each module if section-specific duration is not set.'),
        ),
    ]
