# Generated by Django 5.1.5 on 2026-04-07 18:31

import apps.sat.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0012_globalevent_english_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an icon or photo for this test.', null=True, storage=apps.sat.storages.PublicStorage(), upload_to='sat/test_icons', verbose_name='Icon'),
        ),
    ]
