# Generated by ChatGPT for classroom type split.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0016_classroommembership_left_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(
                choices=[('sat', 'SAT Classroom'), ('ap', 'AP Classroom')],
                db_index=True,
                default='sat',
                max_length=10,
            ),
        ),
    ]
