# Generated by Django 5.1.5 on 2026-05-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0018_scope_sat_attempts_by_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreview',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
