# Generated by Django 5.1.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0023_vocabulary_learning_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModuleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attempt_id', models.UUIDField(editable=False)),
                ('section', models.CharField(max_length=8)),
                ('module', models.CharField(max_length=8)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('time_spent', models.JSONField(blank=True, default=list)),
                ('eliminated_choices', models.JSONField(blank=True, default=list)),
                ('marked_for_review', models.JSONField(blank=True, default=list)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('deadline_at', models.DateTimeField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_module_drafts', to='sat.classroom')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_drafts', to='sat.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_module_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='testmoduledraft',
            constraint=models.UniqueConstraint(fields=('user', 'test', 'attempt_id', 'section', 'module'), name='sat_unique_module_draft'),
        ),
        migrations.AddIndex(
            model_name='testmoduledraft',
            index=models.Index(fields=['user', 'test', 'attempt_id'], name='sat_tmd_u_t_att'),
        ),
        migrations.AddIndex(
            model_name='testmoduledraft',
            index=models.Index(fields=['deadline_at'], name='sat_tmd_deadline'),
        ),
    ]
