# Generated by Django 5.1.5 on 2026-07-21 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0028_support_teacher_public_profile_v29'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('average_sat_score', models.PositiveSmallIntegerField(help_text='Planning reference shown to students. Keep this value updated from your trusted source.', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(1600)])),
                ('score_note', models.CharField(blank=True, help_text='Optional context, for example: typical admitted-student range or internal target.', max_length=180)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dream University',
                'verbose_name_plural': 'Dream Universities',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='sat_unique_dream_university_country')],
            },
        ),
        migrations.CreateModel(
            name='StudentGoalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('custom_university_name', models.CharField(blank=True, max_length=180)),
                ('custom_university_country', models.CharField(blank=True, max_length=120)),
                ('custom_average_sat_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(1600)])),
                ('target_sat_score', models.PositiveSmallIntegerField(default=1400, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(1600)])),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('daily_study_minutes_goal', models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(360)])),
                ('weekly_study_days_goal', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('dream_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_goals', to='sat.dreamuniversity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sat_goal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student SAT Goal',
                'verbose_name_plural': 'Student SAT Goals',
            },
        ),
    ]
