# Generated for MakonBook student goal dashboard v32

import django.core.validators
from django.db import migrations, models


UNIVERSITIES = [(1, 'Massachusetts Institute of Technology (MIT)', 'Cambridge', 'United States'),
 (2, 'Imperial College London', 'London', 'United Kingdom'),
 (2, 'Stanford University', 'Stanford', 'United States'),
 (4, 'University of Oxford', 'Oxford', 'United Kingdom'),
 (5, 'Harvard University', 'Cambridge', 'United States'),
 (6, 'University of Cambridge', 'Cambridge', 'United Kingdom'),
 (7, 'California Institute of Technology (Caltech)', 'Pasadena', 'United States'),
 (8, 'ETH Zurich', 'Zürich', 'Switzerland'),
 (8, 'UCL', 'London', 'United Kingdom'),
 (10, 'National University of Singapore (NUS)', 'Singapore', 'Singapore'),
 (11, 'The University of Hong Kong', 'Hong Kong', 'Hong Kong SAR'),
 (12, 'Nanyang Technological University, Singapore (NTU Singapore)', 'Singapore', 'Singapore'),
 (13, 'Peking University', 'Beijing', 'China (Mainland)'),
 (14, 'Tsinghua University', 'Beijing', 'China (Mainland)'),
 (15, 'University of Pennsylvania', 'Philadelphia', 'United States'),
 (16, 'Cornell University', 'Ithaca', 'United States'),
 (16, 'Yale University', 'New Haven', 'United States'),
 (18, 'The Chinese University of Hong Kong (CUHK)', 'Hong Kong', 'Hong Kong SAR'),
 (19, 'The University of New South Wales (UNSW Sydney)', 'Sydney', 'Australia'),
 (20, 'Johns Hopkins University', 'Baltimore', 'United States'),
 (20, 'University of California, Berkeley (UCB)', 'Berkeley', 'United States'),
 (22, 'EPFL – École polytechnique fédérale de Lausanne', 'Lausanne', 'Switzerland'),
 (22, 'The University of Melbourne', 'Melbourne', 'Australia'),
 (24, 'University of Chicago', 'Chicago', 'United States'),
 (25, 'Technical University of Munich', 'Munich', 'Germany'),
 (26, 'Fudan University', 'Shanghai', 'China (Mainland)'),
 (27, 'Princeton University', 'Princeton', 'United States'),
 (28, 'The University of Sydney', 'Sydney', 'Australia'),
 (29, 'Australian National University (ANU)', 'Canberra', 'Australia'),
 (30, 'McGill University', 'Montreal', 'Canada'),
 (31, 'Monash University', 'Melbourne', 'Australia'),
 (32, 'University of Toronto', 'Toronto', 'Canada'),
 (33, 'The Hong Kong University of Science and Technology', 'Hong Kong', 'Hong Kong SAR'),
 (34, 'Université PSL', 'Paris', 'France'),
 (35, 'The University of Edinburgh', 'Edinburgh', 'United Kingdom'),
 (36, 'Shanghai Jiao Tong University', 'Shanghai', 'China (Mainland)'),
 (37, "King's College London", 'London', 'United Kingdom'),
 (38, 'Seoul National University', 'Seoul', 'South Korea'),
 (39, 'The University of Tokyo', 'Tokyo', 'Japan'),
 (40, 'The University of Manchester', 'Manchester', 'United Kingdom'),
 (40, 'The University of Queensland', 'Brisbane City', 'Australia'),
 (42, 'Yonsei University', 'Seoul', 'South Korea'),
 (43, 'Columbia University', 'New York City', 'United States'),
 (43, 'Institut Polytechnique de Paris', 'Paris', 'France'),
 (45, 'Northwestern University', 'Evanston', 'United States'),
 (45, 'University of British Columbia', 'Vancouver', 'Canada'),
 (47, 'Zhejiang University', 'Hangzhou', 'China (Mainland)'),
 (48, 'Delft University of Technology', 'Delft', 'Netherlands'),
 (49, 'University of California, Los Angeles (UCLA)', 'Los Angeles', 'United States'),
 (50, 'The Hong Kong Polytechnic University', 'Hong Kong', 'Hong Kong SAR'),
 (51, 'University of Michigan-Ann Arbor', 'Ann Arbor', 'United States'),
 (52, 'City University of Hong Kong (CityUHK)', 'Kowloon', 'Hong Kong SAR'),
 (52, 'Korea University', 'Seoul', 'South Korea'),
 (54, 'National Taiwan University (NTU)', 'Taipei', 'Taiwan'),
 (55, 'Carnegie Mellon University', 'Pittsburgh', 'United States'),
 (56, 'Universiti Malaya (UM)', 'Kuala Lumpur', 'Malaysia'),
 (57, 'University of Bristol', 'Bristol', 'United Kingdom'),
 (58, 'New York University (NYU)', 'New York City', 'United States'),
 (59, 'KU Leuven', 'Leuven', 'Belgium'),
 (60, 'University of Amsterdam', 'Amsterdam', 'Netherlands'),
 (61, 'Ludwig-Maximilians-Universität München', 'Munich', 'Germany'),
 (62, 'The London School of Economics and Political Science (LSE)', 'London', 'United Kingdom'),
 (63, 'KFUPM', 'Dhahran', 'Saudi Arabia'),
 (64, 'Kyoto University', 'Kyoto', 'Japan'),
 (65, 'KAIST', 'Daejeon', 'South Korea'),
 (66, 'Brown University', 'Providence', 'United States'),
 (67, 'The University of Auckland', 'Auckland', 'New Zealand'),
 (68, 'University of Warwick', 'England', 'United Kingdom'),
 (68, 'University of Birmingham', 'Birmingham', 'United Kingdom'),
 (70, 'Duke University', 'Durham', 'United States'),
 (71, 'Lund University', 'Lund', 'Sweden'),
 (72, 'University of Texas at Austin', 'Austin', 'United States'),
 (73, 'Sorbonne University', 'Paris', 'France'),
 (74, 'University of Illinois Urbana-Champaign', 'Champaign', 'United States'),
 (75, 'Trinity College Dublin, The University of Dublin', 'Dublin', 'Ireland'),
 (76, 'Université Paris-Saclay', 'Paris', 'France'),
 (77, 'The University of Western Australia', 'Perth', 'Australia'),
 (77, 'University of Leeds', 'Leeds', 'United Kingdom'),
 (79, 'Adelaide University', 'Adelaide', 'Australia'),
 (80, 'University of Glasgow', 'Glasgow', 'United Kingdom'),
 (81, 'University of California, San Diego (UCSD)', 'San Diego', 'United States'),
 (82, 'KTH Royal Institute of Technology', 'Stockholm', 'Sweden'),
 (82, 'The University of Sheffield', 'Sheffield', 'United Kingdom'),
 (84, 'Universidad de Buenos Aires (UBA)', 'Buenos Aires', 'Argentina'),
 (85, 'Durham University', 'Durham', 'United Kingdom'),
 (86, 'Universität Heidelberg', 'Heidelberg', 'Germany'),
 (87, 'Politecnico di Milano', 'Milan', 'Italy'),
 (87, 'The University of Technology Sydney (UTS)', 'Sydney', 'Australia'),
 (87, 'Uppsala University', 'Uppsala', 'Sweden'),
 (90, 'Nanjing University', 'Nanjing', 'China (Mainland)'),
 (90, 'University of Copenhagen', 'Copenhagen', 'Denmark'),
 (92, 'Pennsylvania State University', 'University Park', 'United States'),
 (92, 'University of Washington', 'Seattle', 'United States'),
 (94, 'Boston University', 'Boston', 'United States'),
 (95, 'The University of Osaka', 'Osaka City', 'Japan'),
 (96, 'University of Alberta', 'Edmonton', 'Canada'),
 (97, 'Institute of Science Tokyo', 'Tokyo', 'Japan'),
 (97, 'University of Nottingham', 'Nottingham', 'United Kingdom'),
 (98, 'Freie Universitaet Berlin', 'Berlin', 'Germany'),
 (98, 'University of Zurich', 'Zürich', 'Switzerland'),
 (100, 'Purdue University', 'West Lafayette', 'United States'),
 (100, 'University College Dublin', 'Dublin', 'Ireland'),
 (102, 'Tohoku University', 'Sendai City', 'Japan'),
 (103, 'Queen Mary University of London', 'London', 'United Kingdom'),
 (104, 'RWTH Aachen University', 'Aachen', 'Germany'),
 (105, 'Technical University of Denmark', 'Kongens Lyngby', 'Denmark'),
 (106, 'Pohang University of Science And Technology (POSTECH)', 'Pohang', 'South Korea'),
 (107, 'King Saud University', 'Riyadh', 'Saudi Arabia'),
 (108, 'Sungkyunkwan University (SKKU)', 'Seoul', 'South Korea'),
 (109, 'Qatar University', 'Doha', 'Qatar'),
 (110, 'KIT, Karlsruhe Institute of Technology', 'Karlsruhe', 'Germany'),
 (111, 'Sapienza University of Rome', 'Rome', 'Italy'),
 (111, 'University of Southampton', 'Southampton', 'United Kingdom'),
 (113, 'University of Waterloo', 'Waterloo', 'Canada'),
 (113, 'Utrecht University', 'Utrecht', 'Netherlands'),
 (115, 'Lomonosov Moscow State University', 'Moscow', 'Russia'),
 (115, 'University of St Andrews', 'St. Andrews', 'United Kingdom'),
 (118, 'Indian Institute of Technology Delhi (IITD)', 'New Delhi', 'India'),
 (119, 'Leiden University', 'Leiden', 'Netherlands'),
 (119, 'Pontificia Universidad Católica de Chile (UC)', 'Santiago', 'Chile'),
 (119, 'RMIT University', 'Melbourne', 'Australia'),
 (122, 'Rice University', 'Houston', 'United States'),
 (123, 'Alma Mater Studiorum - Università di Bologna', 'Bologna', 'Italy'),
 (123, 'University of Helsinki', 'Helsinki', 'Finland'),
 (125, 'University of Bath', 'Bath', 'United Kingdom'),
 (126, 'Aalto University', 'Espoo', 'Finland'),
 (126, 'Macquarie University (Sydney, Australia)', 'Sydney', 'Australia'),
 (128, 'Aarhus University', 'Aarhus', 'Denmark'),
 (128, 'Universiti Sains Malaysia (USM)', 'Gelugor', 'Malaysia'),
 (130, 'Universiti Kebangsaan Malaysia (UKM)', 'Bangi', 'Malaysia'),
 (131, 'University of Oslo', 'Oslo', 'Norway'),
 (131, 'University of Wisconsin-Madison', 'Madison', 'United States'),
 (133, 'Universidade de São Paulo', 'São Paulo', 'Brazil'),
 (134, 'Indian Institute of Technology Bombay (IITB)', 'Mumbai', 'India'),
 (134, 'University of Science and Technology of China', 'Hefei', 'China (Mainland)'),
 (136, 'University of Exeter', 'Exeter', 'United Kingdom'),
 (137, 'University of California, Davis', 'Davis', 'United States'),
 (138, 'Universiti Putra Malaysia (UPM)', 'Serdang', 'Malaysia'),
 (139, 'University of Liverpool', 'Liverpool', 'United Kingdom'),
 (140, 'Humboldt-Universität zu Berlin', 'Berlin', 'Germany'),
 (140, 'University of Vienna', 'Vienna', 'Austria'),
 (142, 'Georgia Institute of Technology', 'Atlanta', 'United States'),
 (142, 'National Tsing Hua University - NTHU', 'Hsinchu City', 'Taiwan'),
 (142, 'Western University', 'London', 'Canada'),
 (145, 'Universidad Nacional Autónoma de México (UNAM)', 'Mexico City', 'Mexico'),
 (146, 'Tongji University', 'Shanghai', 'China (Mainland)'),
 (147, 'Khalifa University', 'Abu Dhabi', 'United Arab Emirates'),
 (148, 'Erasmus University Rotterdam', 'Rotterdam', 'Netherlands'),
 (149, 'Newcastle University', 'Newcastle upon Tyne', 'United Kingdom'),
 (150, 'Ghent University', 'Ghent', 'Belgium'),
 (150, 'University of Basel', 'Basel', 'Switzerland'),
 (152, 'Eindhoven University of Technology', 'Eindhoven', 'Netherlands'),
 (153, 'University of Southern California', 'Los Angeles', 'United States'),
 (154, 'Wageningen University & Research', 'Wageningen', 'Netherlands'),
 (155, 'Hanyang University', 'Seoul', 'South Korea'),
 (156, 'Nagoya University', 'Nagoya', 'Japan'),
 (157, 'University of Groningen', 'Groningen', 'Netherlands'),
 (158, 'Technische Universität Berlin (TU Berlin)', 'Berlin', 'Germany'),
 (158, 'Universiti Teknologi Malaysia', 'Skudai', 'Malaysia'),
 (158, 'University of North Carolina at Chapel Hill', 'Chapel Hill', 'United States'),
 (158, 'University of York', 'York', 'United Kingdom'),
 (162, 'Université de Montréal', 'Montreal', 'Canada'),
 (162, 'Washington University in St. Louis', 'St. Louis', 'United States'),
 (164, 'Lancaster University', 'Lancaster', 'United Kingdom'),
 (165, 'Universitat de Barcelona', 'Barcelona', 'Spain'),
 (165, 'Wuhan University', 'Wuhan', 'China (Mainland)'),
 (167, 'Stockholm University', 'Stockholm', 'Sweden'),
 (168, 'University of Geneva', 'Geneva', 'Switzerland'),
 (169, 'Texas A&M University', 'College Station', 'United States'),
 (170, 'Indian Institute of Technology Madras (IITM)', 'Chennai', 'India'),
 (171, 'Kyushu University', 'Fukuoka City', 'Japan'),
 (172, 'Arizona State University', 'Phoenix', 'United States'),
 (173, 'University of California, Santa Barbara (UCSB)', 'Santa Barbara', 'United States'),
 (174, 'Chalmers University of Technology', 'Gothenburg', 'Sweden'),
 (174, 'McMaster University', 'Hamilton', 'Canada'),
 (174, "Queen's University Belfast", 'Belfast', 'United Kingdom'),
 (177, 'Al-Farabi Kazakh National University', 'Almaty', 'Kazakhstan'),
 (177, 'National Yang Ming Chiao Tung University (NYCU Taiwan)', 'Hsinchu City', 'Taiwan'),
 (179, 'Cardiff University', 'Cardiff', 'United Kingdom'),
 (179, 'Hokkaido University', 'Sapporo', 'Japan'),
 (179, "Queen's University at Kingston", 'Kingston', 'Canada'),
 (182, 'Michigan State University', 'East Lansing', 'United States'),
 (183, 'Emory University', 'Atlanta', 'United States'),
 (184, 'University of Cape Town', 'Cape Town', 'South Africa'),
 (185, 'Technische Universität Dresden', 'Dresden', 'Germany'),
 (185, 'Universidad de Chile', 'Santiago', 'Chile'),
 (185, 'Vrije Universiteit Amsterdam', 'Amsterdam', 'Netherlands'),
 (188, 'Tecnológico de Monterrey', 'Monterrey', 'Mexico'),
 (189, 'Curtin University', 'Perth', 'Australia'),
 (190, 'Harbin Institute of Technology', 'Harbin', 'China (Mainland)'),
 (191, 'National Cheng Kung University (NCKU)', 'Tainan City', 'Taiwan'),
 (191, 'Technische Universität Wien', 'Vienna', 'Austria'),
 (191, 'Universitas Indonesia', 'Depok', 'Indonesia'),
 (191, 'University of Bern', 'Bern', 'Switzerland'),
 (195, 'University of Wollongong', 'Wollongong', 'Australia'),
 (196, 'Université catholique de Louvain (UCLouvain)', 'Louvain-la-Neuve', 'Belgium'),
 (196, 'University of Reading', 'Reading', 'United Kingdom'),
 (198, 'University of Otago', 'Dunedin', 'New Zealand'),
 (199, 'Complutense University of Madrid', 'Madrid', 'Spain'),
 (200, 'King Abdulaziz University (KAU)', 'Jeddah', 'Saudi Arabia')]


def seed_qs_top_200(apps, schema_editor):
    DreamUniversity = apps.get_model('sat', 'DreamUniversity')
    for sort_order, (rank, name, city, country) in enumerate(UNIVERSITIES, start=1):
        university, created = DreamUniversity.objects.get_or_create(
            name=name,
            country=country,
            defaults={
                'city': city,
                'average_sat_score': None,
                'qs_rank': rank,
                'ranking_source': 'QS World University Rankings',
                'ranking_year': 2027,
                'score_note': f'QS World University Rankings 2027: #{rank}. SAT average not published or not applicable.',
                'is_active': True,
                'sort_order': sort_order,
            },
        )
        update_fields = []
        desired = {
            'city': city,
            'qs_rank': rank,
            'ranking_source': 'QS World University Rankings',
            'ranking_year': 2027,
            'is_active': True,
            'sort_order': sort_order,
        }
        for field, value in desired.items():
            if getattr(university, field) != value:
                setattr(university, field, value)
                update_fields.append(field)
        if not university.score_note:
            university.score_note = (
                f'QS World University Rankings 2027: #{rank}. '
                'SAT average not published or not applicable.'
            )
            update_fields.append('score_note')
        if update_fields:
            university.save(update_fields=update_fields)


def unseed_qs_top_200(apps, schema_editor):
    DreamUniversity = apps.get_model('sat', 'DreamUniversity')
    DreamUniversity.objects.filter(
        ranking_source='QS World University Rankings',
        ranking_year=2027,
        student_goals__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0029_student_goal_dashboard_v30'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamuniversity',
            name='average_sat_score',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Optional published or internally verified SAT reference. Do not invent values.',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(400),
                    django.core.validators.MaxValueValidator(1600),
                ],
            ),
        ),
        migrations.AddField(
            model_name='dreamuniversity',
            name='qs_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dreamuniversity',
            name='ranking_source',
            field=models.CharField(
                blank=True,
                default='QS World University Rankings',
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name='dreamuniversity',
            name='ranking_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(seed_qs_top_200, unseed_qs_top_200),
    ]
