Page not found (404)
No GlobalEvent matches the given query.
Request Method:	GET
Request URL:	http://127.0.0.1:8000/sat/global-events/makon-ap-quest-01/leaderboard/
Raised by:	apps.sat.guest_views._wrapped_view
Using the URLconf defined in satmakon.urls, Django tried these URL patterns, in this order:

[name='home']
login/ [name='login']
logout/ [name='logout']
register/ [name='register']
activate/<uuid:token>/ [name='activate']
edit-profile/ [name='edit_profile']
software/ [name='software']
sat/ [name='sat_menu']
sat/ [name='home']
sat/ dashboard/ [name='dashboard']
sat/ clear/<str:test>/<str:section>/<str:module>/
sat/ practise/<str:pk> [name='practise']
sat/ restart/<str:pk> [name='restart']
sat/ restart_section/<str:pk>/<str:section>/ [name='restart_section']
sat/ punishment/<str:pk> [name='punishment']
sat/ results/<str:test> [name='results']
sat/ results/certificate/<str:test>/ [name='results_certificate']
sat/ results/certificate/<str:test>/<str:username> [name='results_certificate_by_user']
sat/ results/<str:test>/<str:username> [name='results_by_user']
sat/ question/<str:key>/<str:section>/<str:module>/<str:id> [name='question']
sat/ practise/<str:pk>/start [name='test']
sat/ check_the_answers [name='check_the_answers']
sat/ rankings/<str:pk> [name='rankings']
sat/ enter-code/ [name='enter_secret_code']
sat/ start-makeup-test/<str:pk>/ [name='start_makeup_test']
sat/ makeup-test-module/<str:pk>/ [name='makeup_test_module']
sat/ dev/
sat/ admin-panel/
sat/ practice_tests/ [name='practice_tests']
sat/ vocabulary/ [name='vocabulary']
sat/ admissions/ [name='admissions']
sat/ vocabulary/practice-quiz/ [name='vocabulary_practice_quiz']
sat/ vocabulary/practice-quiz/start/ [name='vocabulary_practice_quiz_start']
sat/ vocabulary/practice-quiz/result/ [name='vocabulary_practice_quiz_result']
sat/ vocabulary/<slug:slug>/ [name='vocabulary_section']
sat/ admissions/<slug:slug>/ [name='admissions_section']
sat/ teacher/classrooms/ [name='teacher_classroom_list']
sat/ teacher/classrooms/create/ [name='create_classroom']
sat/ teacher/classrooms/<int:classroom_id>/ [name='teacher_classroom_dashboard']
sat/ teacher/classrooms/<int:classroom_id>/generate-code/ [name='generate_classroom_join_code']
sat/ join/ [name='submit_classroom_join_request']
sat/ join/status/ [name='classroom_join_status']
sat/ classroom/<int:classroom_id>/ [name='student_classroom_home']
sat/ teacher/classrooms/<int:classroom_id>/requests/ [name='classroom_join_requests']
sat/ teacher/classrooms/<int:classroom_id>/requests/<int:membership_id>/approve/ [name='approve_join_request']
sat/ teacher/classrooms/<int:classroom_id>/requests/<int:membership_id>/reject/ [name='reject_join_request']
sat/ teacher/classrooms/<int:classroom_id>/students/<int:user_id>/access/ [name='update_student_section_access']
sat/ teacher/classrooms/<int:classroom_id>/students/<int:user_id>/remove/ [name='remove_student_from_classroom']
sat/ teacher/classrooms/<int:classroom_id>/section-access/ [name='update_classroom_section_access']
sat/ classroom/<int:classroom_id>/practice-tests/ [name='classroom_practice_tests']
sat/ classroom/<int:classroom_id>/practice/<str:pk>/start/ [name='classroom_practise']
sat/ classroom/<int:classroom_id>/practice/<str:pk>/module/ [name='classroom_test']
sat/ teacher/classrooms/<int:classroom_id>/practice-tests/access/ [name='update_classroom_practice_test_access']
sat/ classroom/<int:classroom_id>/vocabulary/ [name='classroom_vocabulary']
sat/ classroom/<int:classroom_id>/vocabulary/<slug:slug>/ [name='classroom_vocabulary_section']
sat/ classroom/<int:classroom_id>/vocabulary/practice-quiz/start/ [name='classroom_vocabulary_practice_quiz_start']
sat/ classroom/<int:classroom_id>/vocabulary/practice-quiz/result/ [name='classroom_vocabulary_practice_quiz_result']
sat/ classroom/<int:classroom_id>/admissions/ [name='classroom_admissions']
sat/ teacher/classrooms/<int:classroom_id>/progress/ [name='classroom_progress_dashboard']
sat/ teacher/classrooms/<int:classroom_id>/progress/student/<int:student_id>/practice/ [name='classroom_student_practice_progress']
sat/ teacher/classrooms/<int:classroom_id>/progress/student/<int:student_id>/vocabulary/ [name='classroom_student_vocab_progress']
sat/ teacher/classrooms/<int:classroom_id>/progress/student/<int:student_id>/admissions/ [name='classroom_student_admission_progress']
sat/ teacher/classrooms/<int:classroom_id>/progress/student/<int:student_id>/practice/<str:test_name>/review/ [name='classroom_student_review_results']
sat/ teacher/classrooms/<int:classroom_id>/progress/student/<int:student_id>/review/<str:key>/<str:section>/<str:module>/<str:id>/ [name='classroom_student_review_question']
sat/ classroom/<int:classroom_id>/chat/ [name='classroom_chat']
sat/ classroom/<int:classroom_id>/chat/send/ [name='send_classroom_message']
sat/ classroom/<int:classroom_id>/chat/fetch/ [name='fetch_classroom_messages']
sat/ classroom/<int:classroom_id>/chat/message/<int:message_id>/delete/ [name='delete_classroom_message']
sat/ classroom/<int:classroom_id>/chat/message/<int:message_id>/delete-file/ [name='delete_classroom_message_file']
sat/ teacher/classrooms/<int:classroom_id>/delete/ [name='delete_classroom']
sat/ teacher/classrooms/<int:classroom_id>/edit/ [name='edit_classroom']
sat/ guest/ [name='guest_entry']
sat/ guest/logout/ [name='guest_logout']
sat/ global-events/ [name='global_event_list']
sat/ global-events/<slug:slug>/ [name='global_event_detail']
sat/ global-events/<slug:slug>/start/ [name='start_global_event']
sat/ global-events/attempt/<uuid:guest_token>/ [name='global_event_attempt']
sat/ global-events/attempt/<uuid:guest_token>/save/ [name='save_global_event_answer']
sat/ global-events/attempt/<uuid:guest_token>/submit/ [name='submit_global_event']
sat/ global-events/attempt/<uuid:guest_token>/result/ [name='global_event_result']
sat/ global-events/<slug:slug>/leaderboard/ [name='global_event_leaderboard']
The current path, sat/global-events/makon-ap-quest-01/leaderboard/, matched the last one.

You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.