# Generated by Django 5.1.5 on 2026-03-16 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 9, 9, 34, 896951, tzinfo=datetime.timezone.utc)),
        ),
    ]
