# Generated by Django 5.1.5 on 2026-03-17 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 18, 3, 37, 35, 44775, tzinfo=datetime.timezone.utc)),
        ),
    ]
