# Generated by Django 5.1.5 on 2026-03-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 24, 16, 10, 1, 451114, tzinfo=datetime.timezone.utc)),
        ),
    ]
