# Generated by Django 5.1.5 on 2026-03-24 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 25, 19, 42, 27, 921397, tzinfo=datetime.timezone.utc)),
        ),
    ]
