# Generated by Django 5.1.5 on 2026-03-26 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 11, 19, 23, 462926, tzinfo=datetime.timezone.utc)),
        ),
    ]
