# Generated by Django 5.1.5 on 2026-03-27 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 28, 20, 24, 47, 793670, tzinfo=datetime.timezone.utc)),
        ),
    ]
