# Generated by Django 5.1.5 on 2026-03-28 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 29, 6, 28, 5, 433643, tzinfo=datetime.timezone.utc)),
        ),
    ]
