# Generated by Django 5.1.5 on 2026-04-07 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 6, 5, 51, 364241, tzinfo=datetime.timezone.utc)),
        ),
    ]
