# Generated by Django 5.1.5 on 2026-04-07 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 9, 56, 58, 503166, tzinfo=datetime.timezone.utc)),
        ),
    ]
