# Generated by Django 5.1.5 on 2026-04-07 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 16, 16, 55, 697501, tzinfo=datetime.timezone.utc)),
        ),
    ]
