# Generated by Django 5.1.5 on 2026-04-07 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 18, 3, 19, 579887, tzinfo=datetime.timezone.utc)),
        ),
    ]
