# Generated by Django 5.1.5 on 2026-04-16 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 8, 46, 7, 920417, tzinfo=datetime.timezone.utc)),
        ),
    ]
