# Generated by Django 5.1.5 on 2026-04-16 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 8, 48, 4, 329622, tzinfo=datetime.timezone.utc)),
        ),
    ]
