# Generated by Django 5.1.5 on 2026-04-22 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 17, 33, 8, 811781, tzinfo=datetime.timezone.utc)),
        ),
    ]
