# Generated by Django 5.1.5 on 2026-04-26 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 27, 2, 50, 11, 610801, tzinfo=datetime.timezone.utc)),
        ),
    ]
