# Generated by Django 5.1.5 on 2026-05-01 22:47

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=apps.base.models.email_verification_expiry),
        ),
    ]
