# Generated by Django 5.1.5 on 2026-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apclasses', '0003_apexamattempt_guest_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apexamattempt',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apexamattempt',
            name='guest_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
