# Generated by ChatGPT for AP event-level module timers

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apclasses', '0004_alter_apexamattempt_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apmockexam',
            name='frq_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='FRQ pages shown on screen; students answer on paper'),
        ),
        migrations.AddField(
            model_name='apexamevent',
            name='part_a_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Timer for AP Part A MCQ module'),
        ),
        migrations.AddField(
            model_name='apexamevent',
            name='part_b_duration_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Timer for AP Part B MCQ module'),
        ),
        migrations.AddField(
            model_name='apexamevent',
            name='frq_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Timer for FRQ image pages; students answer on paper'),
        ),
    ]
