# Generated by Django 5.1.5 on 2026-04-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apclasses', '0005_ap_event_module_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apexamevent',
            name='frq_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='apexamevent',
            name='part_a_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='apexamevent',
            name='part_b_duration_minutes',
        ),
    ]
