# Generated by Django 5.1.5 on 2026-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateduser',
            name='password',
            field=models.CharField(blank=True, help_text='Temporary password storage. Raw passwords are hidden in UI and only stored when necessary.', max_length=8),
        ),
    ]
